version: '3' 
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - 8080:8080 
      - 7077:7077 
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-jupyter
    ports:
      - 8888:8888
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
      - spark-worker
